// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewDojo.Data;

#nullable disable

namespace ReviewDojo.Data.Migrations
{
    [DbContext(typeof(ReviewDojoContext))]
    partial class ReviewDojoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ReviewDojo.Data.BugCorpusEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AfterSnippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BeforeSnippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Corpus");
                });

            modelBuilder.Entity("ReviewDojo.Data.Diff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClean")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordinal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeLines")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UnifiedDiffText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Verdict")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Diffs");
                });

            modelBuilder.Entity("ReviewDojo.Data.FindingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DiffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Line")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiffId");

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("ReviewDojo.Data.ManifestEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DiffId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LineEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineStart")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiffId");

                    b.ToTable("ManifestEntries");
                });

            modelBuilder.Entity("ReviewDojo.Data.ScoreRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiffId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FalsePositiveRate")
                        .HasColumnType("REAL");

                    b.Property<string>("MatchesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Precision")
                        .HasColumnType("REAL");

                    b.Property<double>("Recall")
                        .HasColumnType("REAL");

                    b.Property<double>("SeverityWeightedRecall")
                        .HasColumnType("REAL");

                    b.Property<long>("TimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VerdictCorrect")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiffId")
                        .IsUnique();

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("ReviewDojo.Data.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CleanRate")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DifficultyTier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetRepoPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ReviewDojo.Data.Diff", b =>
                {
                    b.HasOne("ReviewDojo.Data.Session", null)
                        .WithMany("Diffs")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewDojo.Data.FindingRecord", b =>
                {
                    b.HasOne("ReviewDojo.Data.Diff", null)
                        .WithMany("Findings")
                        .HasForeignKey("DiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewDojo.Data.ManifestEntry", b =>
                {
                    b.HasOne("ReviewDojo.Data.Diff", null)
                        .WithMany("Manifest")
                        .HasForeignKey("DiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewDojo.Data.ScoreRecord", b =>
                {
                    b.HasOne("ReviewDojo.Data.Diff", null)
                        .WithOne("Score")
                        .HasForeignKey("ReviewDojo.Data.ScoreRecord", "DiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewDojo.Data.Diff", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Manifest");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("ReviewDojo.Data.Session", b =>
                {
                    b.Navigation("Diffs");
                });
#pragma warning restore 612, 618
        }
    }
}
